### PR TITLE
map working

### PR DESCRIPTION
**Pull request by ZhangZelin**
Press the start button on XBOX to get the map, on PS4 press the option button

### CODE REVIEW

**Review by xAmaranth — CHANGES_REQUESTED** [review]
From most critical to least critical:

- Decouple ThirdPersonPlayer.cs from the camera implementation. Recommend using the Observer pattern.

- Comments currently document what the code is doing; however, the code is (mostly) self-documenting. Document why the code works, and why the code is needed. For example, why does there need to be two camera positions that need to get set?

IDE should catch the following adjustments, if you have the suggestions enabled:

- Use var to promote polymorphism.

- Make explicit privacy when possible.

- Follow naming conventions. m_Height might be mapHeight. static mapActive should be MapActive.

**Comment by xAmaranth** [comment]
Also: I tried hitting the Options button on the PS4 control, once by simply fetching and checking out, and once by also merging in your controller branch. Neither did anything.

**Comment by irisong980912** [comment]
I fixed the controller issue for ps4 by changing fire3 from "joystick button 3" to "joystick button 9"

**Review by xAmaranth — APPROVED** [review]

**Comment by xAmaranth** [comment]
Still unclear what some code does (like CameraChangeCounter) but code looks good.

**Pull request merged**
