### PR TITLE
Camera44

### LINKED ISSUE #44: Difficult Camera
The camera is difficult to work with: feels unresponsive, does not follow the player closely enough, is very touchy, or is very shaky/stuttery.

### PR DESCRIPTION
**Pull request by xAmaranth**
Overhauled the way the camera is handled in an attempt to create a snappier, more responsive camera.

Decoupled the player movement and camera scripts; the player movement script no longer affects the camera.

Removed the camera effects that occur during a slingshot; these should be re-implemented in the future. A TODO has been marked to do so.

Added interpolation to the player and camera in the Cassiopeia scene to reduce stuttering.

This PR will close #44 . Merge when the changes will adequately meet those requirements.

### CODE REVIEW

**Review by ZhangZelin — CHANGES_REQUESTED** [review]
Tested on Cassiopeia. New implementation broke the old input settings for xbox controller. Used mouse and keyboard to test.

Some issues I noticed:
-Character can no longer strafe left and right, "A" and "D" key turns the camera instead.
-Character does not rotate with the camera, only faces one direction the entire time.
-Character model visually "jittery" while moving. It looks like it is "shaking/vibrating".
-Why did you comment out the stardust count UI part?

Camera is indeed much smoother than before. Good job!

**Comment by xAmaranth** [comment]
@ZhangZelin Can you verify your observed issues? When I tested the implementation, left + right moves the player, and the camera remains stationary. Test by putting the player underneath a point of reference (like stardust) and press A/D. If the player moves relative to the stardust, then the player is moving; if the player does not move relative to the stardust, then the camera is moving.

Does the character rotate at all? If the character rotates, but not when the camera pans, this is intended; the camera rotating should not rotate the character. If the character is not rotating at all, then I will address that issue.

Can you verify that you have interpolation checked for the Rigidbody of the player and the camera?

I commented out the stardust count because it was causing an error on compile time for me.

**Comment by irisong980912** [comment]
issues I found with the camera
1. Right now the player does not rotate towards the direction of the movement. For example, when the player moves forward with respect to the camera, the player should face forward. (I think Zelin also meant this in his problem 2)
2. left+right does move the character left and right, it shows on the scene but is not clear in the game mode. Initially, I thought the same as Zelin that the camera is rotating around the player. It can be solved if 1 is solved. It is better if the camera also "lags" a bit when the player move left and right.

**Comment by irisong980912** [comment]
I added back the player handle rotation function to solve the problem 1 that I mentioned. That handles player rotation when it is moving.

**Review by irisong980912 — CHANGES_REQUESTED** [review]
things to solve:
1. player jittering for the vertical movement (when coming close to the camera or going too far in the forward direction)
2. add the same "camera lag" effect for the horizontal movement (left and right) to give the player a sense of depth. slow down the left and right movement (can be solved by adding a speed variable or reduce the horizontal key sensitivity levels in the project settings)

**Comment by irisong980912** [comment]
not mouse XY, I mean the player vertical and horizontal key sensitivity level

**Comment by ZhangZelin** [comment]
Just reviewed and tested again as of March 1, 12:00PM. I think this is after the commit that Iris made. 

-The left right strafe seem to be actually moving the character but it turns the camera at the same time too, the camera does not remain stationary. This is what happens when I try to strafe left and right with only "A" and "D": https://gfycat.com/jitteryperiodicbufflehead
-Rotation of character is fixed.
-Character model still "jitters" when moving. It is not that noticeable when moving forward since the camera zooms out a bit and the character is very small on the screen. It is very noticeable when holding down "S" where the character moves backward toward the camera.

**Comment by xAmaranth** [comment]
The character now turns when they move left or right.

I'm not sure what causes the shaking for the character, although it's most pronounced when the character moves into the camera.

If the shaking is a problem, I'll look into it more; however, if it's not significant, we may have to move on for the sake of meeting the milestone.

**Review by irisong980912 — APPROVED** [review]
will merge for the purpose of the milestone. we need to continue working on it after Thursday playtesting

**Pull request merged**
